fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.patch$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: \.patch$
        args:
          - --markdown-linebreak-ext=md
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            --remove-all-unused-imports,
            --ignore-init-module-imports,
            --remove-duplicate-keys,
            --in-place,
          ]
        language: python

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args:
          [
            --strict,
            --ignore-missing-imports,
            --check-untyped-defs,
            --show-error-codes,
          ]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.12.0.1
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt
        language: python
        args:
          - -l
          - -d
          - -i
          - "4"
          - -ci
          - -fn
          - -bn
          - -sr
          - -s
          - -w
        types: [shell]
        require_serial: true
        exclude_types: [bats]
